name: Run Node.js Scripts

on:
  # push:
  #   branches: [main]
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Run scripts
        run: |
          node 1.js
          node 2.js
          node 3.js

      - name: Set Git author
        run: |
            git config user.name "plsy1"
            git config user.email "plsy1@users.noreply.github.com"

      - name: Make changes
        run: |
          git add .
          git commit -m "Update" || echo "No changes"
          git push